version: "3.9"

services:
  mysql:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: sf_arcadia
      MYSQL_USER: adminArcadia
      MYSQL_PASSWORD: arcadia123$
      DATABASE_URL: mysql://root:wyguXFroCYhESoTprQNvtMJSoPlpohJo@autorack.proxy.rlwy.net:25214/railway
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - symfony

  php:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      DATABASE_URL: "mysql://ljdbwvhgivks7gxo:dqvxz4v7n0pco32u@tj5iv8piornf713y.cbetxkdyhwsb.us-east-1.rds.amazonaws.com:3306/r1kou6d4xdy6q9er"
    volumes:
      - ./app:/var/www/html
    working_dir: /var/www/html
    depends_on:
      - mysql

  nginx:
  image: nginx:latest
  ports:
    - "8080:80"
  volumes:
    - ./app:/var/www/html
    - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
  depends_on:
    - php

networks:
  symfony:
    driver: bridge

volumes:
  mysql_data:
    driver: local
